# Generated by Django 2.2.10 on 2020-05-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('item_amount', models.FloatField()),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_gen_app.user_lists')),
            ],
        ),
    ]
