# Generated by Django 2.2.10 on 2020-05-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_gen_app', '0002_list_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='list_item',
            name='item_amount',
        ),
        migrations.RemoveField(
            model_name='list_item',
            name='item_id',
        ),
    ]
