# Generated by Django 2.2.10 on 2020-05-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_gen_app', '0003_auto_20200509_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='item',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='list_item',
            name='item_amount',
            field=models.FloatField(default='0.0'),
        ),
    ]
