# Generated by Django 2.2.10 on 2020-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_gen_app', '0004_auto_20200509_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_item',
            name='item_unit',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
